src/Entity/Client.php
<?php

namespace App\Entity;

use App\Repository\ClientRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ClientRepository::class)]
class Client
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\OneToOne(cascade: ['persist', 'remove'])]
    private ?User $user = null;

    #[ORM\OneToMany(mappedBy: 'client', targetEntity: Order::class)]
    private Collection $orders;

    #[ORM\OneToMany(mappedBy: 'client', targetEntity: ClientOffer::class)]
    private Collection $clientOffers;

    #[ORM\OneToMany(mappedBy: 'client', targetEntity: SpecialistRating::class)]
    private Collection $specialistRatings;

    public function __construct()
    {
        $this->orders = new ArrayCollection();
        $this->clientOffers = new ArrayCollection();
        $this->specialistRatings = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUserId(): ?User
    {
        return $this->user;
    }

    public function setUserId(?User $user_id): self
    {
        $this->user = $user_id;

        return $this;
    }

    /**
     * @return Collection<int, Order>
     */
    public function getOrders(): Collection
    {
        return $this->orders;
    }

    public function addOrder(Order $order): self
    {
        if (!$this->orders->contains($order)) {
            $this->orders->add($order);
            $order->setClient($this);
        }

        return $this;
    }

    public function removeOrder(Order $order): self
    {
        if ($this->orders->removeElement($order)) {
            // set the owning side to null (unless already changed)
            if ($order->getClient() === $this) {
                $order->setClient(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, ClientOffer>
     */
    public function getClientOffers(): Collection
    {
        return $this->clientOffers;
    }

    public function addClientOffer(ClientOffer $clientOffer): self
    {
        if (!$this->clientOffers->contains($clientOffer)) {
            $this->clientOffers->add($clientOffer);
            $clientOffer->setClient($this);
        }

        return $this;
    }

    public function removeClientOffer(ClientOffer $clientOffer): self
    {
        if ($this->clientOffers->removeElement($clientOffer)) {
            // set the owning side to null (unless already changed)
            if ($clientOffer->getClient() === $this) {
                $clientOffer->setClient(null);
            }
        }

        return $this;
    }

    public function __toString(): string
    {
        return $this->user->getEmail();
    }

    /**
     * @return Collection<int, SpecialistRating>
     */
    public function getSpecialistRatings(): Collection
    {
        return $this->specialistRatings;
    }

    public function addSpecialistRating(SpecialistRating $specialistRating): self
    {
        if (!$this->specialistRatings->contains($specialistRating)) {
            $this->specialistRatings->add($specialistRating);
            $specialistRating->setClient($this);
        }

        return $this;
    }

    public function removeSpecialistRating(SpecialistRating $specialistRating): self
    {
        if ($this->specialistRatings->removeElement($specialistRating)) {
            // set the owning side to null (unless already changed)
            if ($specialistRating->getClient() === $this) {
                $specialistRating->setClient(null);
            }
        }

        return $this;
    }
}

src/Controller/ClientController.php
<?php

namespace App\Controller;


use App\Entity\Client;
use App\Entity\ClientOffer;
use App\Entity\Order;
use App\Entity\OrderState;
use App\Entity\Specialist;
use App\Entity\SpecialistRating;
use App\Entity\SpecialistRespond;
use App\Entity\User;
use App\Form\OrderFormType;
use App\Form\RatingFormType;
use App\Repository\OrderRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Bundle\SecurityBundle\Security;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;


class ClientController extends AbstractController
{
    public function __construct(private EntityManagerInterface $entityManager,
                                private OrderRepository $orderRepository,
                                private Security $security)
    {
    }

    #[Route('/client/profile', name: 'app_client_profile')]
    public function clientProfile(): Response
    {
        $client = $this->getCurrentClient();

        return $this->render('client/profile.html.twig', [
            'client' => $client,
        ]);
    }

    #[Route('/client/orders', name: 'app_client_homepage')]
    public function orders(): Response
    {
        $orderStateRepository = $this->entityManager->getRepository(OrderState::class);
        $client = $this->getCurrentClient();

        $inPendingStateId = $orderStateRepository->findOneBy(['stateName' => 'STATE_IN_PENDING'])->getId();
        $inProgressStateId = $orderStateRepository->findOneBy(['stateName' => 'STATE_IN_PROGRESS'])->getId();
        $archivedStateId = $orderStateRepository->findOneBy(['stateName' => 'STATE_ARCHIVE'])->getId();

        $notAppointedOrders = $this->orderRepository->findByNotAppointedSpecialists($inPendingStateId, $client->getId());

        $appointedOrders = $this->orderRepository->findByAppointedSpecialist($inProgressStateId, $client->getId());

        $archivedOrders = $this->orderRepository->findByArchivedOrders($archivedStateId, $client->getId());

        return $this->render('client/orders.html.twig', [
            'notAppointedOrders' => $notAppointedOrders,
            'appointedOrders' => $appointedOrders,
            'archivedOrders' => $archivedOrders,
        ]);
    }

    #[Route('/client/rating_to_specialist/{id}', name: 'app_client_leave_feedback')]
    public function leaveFeedbackForSpecialist(int $id, Request $request): Response
    {
        $feedback = new SpecialistRating();
        $form = $this->createForm(RatingFormType::class, $feedback);
        $form->handleRequest($request);

        $client = $this->getCurrentClient();

        $specialist = $this->entityManager->getRepository(Specialist::class)->find($id);

        if ($form->isSubmitted() && $form->isValid()) {

            $currentDate = new \DateTimeImmutable('now');

            $feedback->setRatingText($form->get('ratingText')->getData());
            $feedback->setRating($request->get('rate'));
            $feedback->setCreatedAt($currentDate);
            $feedback->setClient($client);
            $feedback->setSpecialist($specialist);

            $this->entityManager->persist($feedback);
            $this->entityManager->flush();

            return $this->redirectToRoute('app_client_homepage');
        }

        return $this->render('client/create_rating_to_spec.html.twig', [
            'feedbackForm' => $form->createView(),
            'specialist' => $specialist,
        ]);
    }

    #[Route('/client/orders/create', name: 'app_client_create_order')]
    public function createOrder(Request $request): Response
    {
        $order = new Order();
        $form = $this->createForm(OrderFormType::class, $order);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $order->setOrderName($form->get('orderName')->getData());
            $order->setDescription($form->get('description')->getData());
            $order->setCost($form->get('cost')->getData());

            $client = $this->getCurrentClient();

            $order->setClient($client);

            $orderState = $this->entityManager->getRepository(OrderState::class)->findOneBy(['stateName' => 'STATE_IN_PENDING']);

            $order->setOrderState($orderState);
            $order->setCreatedAt(new \DateTimeImmutable('now'));
            $order->setUpdatedAt(new \DateTimeImmutable('now'));

            $this->entityManager->persist($order);
            $this->entityManager->flush();

            return $this->redirectToRoute('app_client_homepage');
        }

        return $this->render('client/create_order.html.twig', [
            'createOrderForm' => $form->createView(),
        ]);
    }

    #[Route('/client/orders/edit/{id}', name: 'app_client_update_order', methods: ['GET', 'POST'])]
    public function updateOrder(int $id, Request $request): Response
    {
        $order = $this->orderRepository->find($id);
        $form = $this->createForm(OrderFormType::class, $order);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

        }

        return $this->render('client/update_order.html.twig', [
            'updateForm' => $form->createView(),
            'order' => $order,
        ]);
    }

    #[Route('/client/orders/delete/{id}', name: 'app_client_delete_order', methods: ['GET', 'DELETE'])]
    public function deleteOrder(int $id): Response
    {
        $order = $this->orderRepository->find($id);

        $this->entityManager->remove($order);
        $this->entityManager->flush();

        return $this->redirectToRoute('app_client_homepage');
    }

    #[Route('/client/orders/complete/{id}', name: 'app_client_complete_order', methods: ['GET'])]
    public function completeOrder(int $id): Response
    {
        $order = $this->orderRepository->find($id);

        $orderStateRepository = $this->entityManager->getRepository(OrderState::class);

        $archivedState = $orderStateRepository->findOneBy(['stateName' => 'STATE_ARCHIVE']);

        $order->setOrderState($archivedState);

        $this->entityManager->persist($order);
        $this->entityManager->flush();

        return $this->redirectToRoute('app_client_homepage');
    }


    #[Route('/client/specialist_profile/{id}', name: 'app_client_specialist_profile')]
    public function showSpecialistProfile(int $id): Response
    {
        $specialistRepository = $this->entityManager->getRepository(Specialist::class);

        $specialist = $specialistRepository->find($id);

        return $this->render('client/specialist_profile.html.twig', [
            'specialist' => $specialist,
        ]);
    }

    #[Route('/client/orders/{id}', name: 'app_client_show_order', methods: ['GET'])]
    public function showOrder(int $id): Response
    {
        $order = $this->orderRepository->find($id);

        return $this->render('client/show_order.html.twig', [
            'order' => $order,
        ]);
    }

    #[Route('/client/orders/{id}/specialists', name: 'app_client_available_specialists')]
    public function showAvailableSpecialists(int $id, Request $request): Response
    {
        $order = $this->orderRepository->find($id);

        $specialistRepository = $this->entityManager->getRepository(Specialist::class);

        $specialists = $specialistRepository->findAll();

        return $this->render('client/search_specialists.html.twig', [
            'specialists' => $specialists,
            'order' => $order,
        ]);
    }

    #[Route('/client/orders/{orderId}/specialists/{specId}', name: 'app_client_offer_order_to_specialist')]
    public function offerOrderToSpecialist(int $orderId, int $specId): Response
    {
        $client = $this->getCurrentClient();

        $specialistRepository = $this->entityManager->getRepository(Specialist::class);
        $specialist = $specialistRepository->find($specId);

        $order = $this->orderRepository->find($orderId);

        $offer = new ClientOffer();

        $offer->setOrder($order);
        $offer->setClient($client);
        $offer->setSpecialist($specialist);

        $offerRepository = $this->entityManager->getRepository(ClientOffer::class);

        if (!$offerRepository->findBy(['client' => $client, 'order' => $order, 'specialist' => $specialist])) {
            $this->entityManager->persist($offer);
            $this->entityManager->flush();
        } else {
            print '<script>alert("Вы уже отправили заявку этому пользователю.")</script>';
        }

        return $this->redirectToRoute('app_client_available_specialists', ['id' => $orderId]);
    }

    #[Route('/client/orders/{id}/related_specialists', name: 'app_client_related_specialists')]
    public function orderRelatedSpecialists(int $id, Request $request): Response
    {
        $order = $this->orderRepository->find($id);
        $client = $this->getCurrentClient();

        $offerRepository = $this->entityManager->getRepository(ClientOffer::class);
        $respondRepository = $this->entityManager->getRepository(SpecialistRespond::class);

        $relatedSpecialists = [];

        $relatedOffersByClient = $offerRepository->findBy(['order' => $order, 'client' => $client]);
        $relatedRespondsBySpec = $respondRepository->findBy(['order' => $order]);

        $relatedSpecialists = array_merge($relatedSpecialists, $relatedOffersByClient);

        foreach ($relatedRespondsBySpec as $respond) {
            foreach ($relatedOffersByClient as $offer) {
                if ($respond->getOrderId() !== $offer->getOrder()) {
                    $relatedSpecialists[] = $respond;
                }
            }
        }

        return $this->render('client/related_specialists.html.twig', [
            'order' => $order,
            'relatedSpecialists' => $relatedSpecialists,
        ]);
    }

templates/client/create_order.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <div style="margin-top: 100px">
        {{ form_start(createOrderForm) }}
            {{ form_row(createOrderForm.orderName) }}
            {{ form_row(createOrderForm.description) }}
            {{ form_row(createOrderForm.cost) }}
            {{ form_row(createOrderForm.address) }}

            <button type="submit">Create</button>

        {{ form_end(createOrderForm) }}
    </div>
{% endblock %}

templates/client/create_rating_to_spec.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <main class="user-profile-main">
        <div class="container">
            <div class="user-profile-content">
                <aside>
                    <nav class="user-nav">
                        <ul>
                            <li><a href="{{ path('app_client_create_order') }}">Новый заказ</a></li>
                            <li><a href="{{ path('app_client_homepage') }}">Мои заказы</a></li>
                            <li><a href="{{ path('app_client_profile') }}">Настройки</a></li>
                            <li><a class="logout" href="{{ path('app_logout') }}">Выйти</a></li>
                        </ul>
                    </nav>
                </aside>
                <main class="client-homepage-main-section">
                    <div class="rating_spec_section">
                        <p>Отзыв на специалиста:
                            <a href="{{ path('app_client_specialist_profile', { id: specialist.id }) }}">
                                {{ specialist.userId.surname }}
                                {{ specialist.userId.firstName }}
                                {{ specialist.userId.patronymic }}
                            </a>
                        </p>
                        <h1>Как вам работа специалиста?</h1>
                    </div>
                    <div>
                        {{ form_start(feedbackForm) }}
                            {{ form_row(feedbackForm.ratingText) }}
                            <p style="font-size: .9rem; color: #777777">В тексте отзыва можно использовать только 1000 символов.</p>

                            <div class="rate">
                                <h2>Оценка</h2>

                                <input type="radio" id="star5" name="rate" value="5" />
                                <label for="star5" title="text">5 stars</label>
                                <input type="radio" id="star4" name="rate" value="4" />
                                <label for="star4" title="text">4 stars</label>
                                <input type="radio" id="star3" name="rate" value="3" />
                                <label for="star3" title="text">3 stars</label>
                                <input type="radio" id="star2" name="rate" value="2" />
                                <label for="star2" title="text">2 stars</label>
                                <input type="radio" id="star1" name="rate" value="1" />
                                <label for="star1" title="text">1 star</label>
                            </div>

                            <button type="submit" class="order-cancel-btn">Оставить отзыв</button>
                        {{ form_end(feedbackForm) }}
                    </div>
                </main>
            </div>
        </div>
    </main>
{% endblock %}

templates/client/orders.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello ClientController!{% endblock %}

{% block body %}
    <main class="user-profile-main">
        <div class="container">
            <div class="user-profile-content">
                <aside>
                    <nav class="user-nav">
                        <ul>
                            <li><a href="{{ path('app_client_create_order') }}">Новый заказ</a></li>
                            <li><a href="{{ path('app_client_homepage') }}">Мои заказы</a></li>
                            <li><a href="{{ path('app_client_profile') }}">Настройки</a></li>
                            <li><a class="logout" href="{{ path('app_logout') }}">Выйти</a></li>
                        </ul>
                    </nav>
                </aside>
                <main class="client-homepage-main-section">
                    <h1>Мои заказы</h1>
                    <nav class="client-homepage-main-section-navbar">
                        <button type="button" class="tabs-btn">В очереди</button>
                        <button type="button" class="tabs-btn">В процессе</button>
                        <button type="button" class="tabs-btn">Архив</button>
                    </nav>
                    <div class="order-tabs-content">
                        <div class="order-list" id="pending">
                            {% for order in notAppointedOrders %}
                                <div class="order-tab">
                                    <h2>{{ order.orderName }}</h2>
                                    <div>
                                        <a href="{{ path('app_client_show_order', { id: order.id }) }}" class="order-info">Детали заказа</a>
{#                                        <p>22.04.2023</p>#}
                                    </div>
                                    <div>
                                        <a href="{{ path('app_client_available_specialists', { id: order.id }) }}">Подобрать специалиста</a>
                                    </div>
                                    <div class="order-tab-button-section">
                                        <a href="{{ path('app_client_related_specialists', { id: order.id }) }}" class="order-cancel-btn">
                                            Перейти к специалистам
                                        </a>
                                        <a href="{{ path('app_client_delete_order', { id: order.id }) }}">
                                            Отменить заказ
                                        </a>
                                    </div>
                                </div>
                            {% endfor %}
                        </div>
                        <div class="order-list" id="inProgress">
                            {% for order in appointedOrders %}
                                <div class="order-tab">
                                    <h2>{{ order.orderName }}</h2>
                                    <div>
                                        <a href="{{ path('app_client_show_order', { id: order.id }) }}" class="order-info">Детали заказа</a>
                                        {#                                        <p>22.04.2023</p>#}
                                    </div>
                                    <div>
                                        <a href="{{ path('app_client_specialist_profile', { id: order.specialist.id }) }}"
                                           class="client_link_to_spec"
                                        >
                                            {{ order.specialist.userId.surname }}
                                            {{ order.specialist.userId.firstName }}
                                            {{ order.specialist.userId.patronymic }}
                                        </a>
                                    </div>
                                    <div class="order-tab-button-section">
                                        <a href="{{ path('app_client_complete_order', { id: order.id }) }}" class="review_btn">
                                            Завершить заказ
                                        </a>
                                        <a href="{{ path('app_client_delete_order', { id: order.id }) }}">
                                            Отменить заказ
                                        </a>
                                    </div>
                                </div>
                            {% endfor %}
                        </div>
                        <div class="order-list" id="archive">
                            {% for order in archivedOrders %}
                                <div class="order-tab">
                                    <h2>{{ order.orderName }}</h2>
                                    <div>
                                        <a href="{{ path('app_client_show_order', { id: order.id }) }}"
                                           class="order-info"
                                        >
                                            Детали заказа
                                        </a>
                                        {#                                        <p>22.04.2023</p>#}
                                    </div>
                                    <div>
                                        <a href="{{ path('app_client_specialist_profile', { id: order.specialist.id }) }}"
                                           class="client_link_to_spec"
                                        >
                                            {{ order.specialist.userId.surname }}
                                            {{ order.specialist.userId.firstName }}
                                            {{ order.specialist.userId.patronymic }}
                                        </a>
                                    </div>
                                    <div>
                                        <a href="{{ path('app_client_leave_feedback', { id: order.specialist.id }) }}" class="review_btn">
                                            Оставить отзыв
                                        </a>
                                    </div>
                                </div>
                            {% endfor %}
                        </div>
                    </div>
                </main>
            </div>
        </div>
    </main>
{% endblock %}

templates/client/profile.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello ClientController!{% endblock %}

{% block body %}
    <main class="user-profile-main">
        <div class="container">
            <div class="user-profile-content">
                <aside>
                    <nav class="user-nav">
                        <ul>
                            <li><a href="{{ path('app_client_create_order') }}">Новый заказ</a></li>
                            <li><a href="{{ path('app_client_homepage') }}">Мои заказы</a></li>
                            <li><a href="{{ path('app_client_profile') }}">Настройки</a></li>
                            <li><a class="logout" href="{{ path('app_logout') }}">Выйти</a></li>
                        </ul>
                    </nav>
                </aside>
                <main class="client-profile-content">
                    <h1>Профиль</h1>
                    <header class="profile-header">
                        <div class="profile-img">
                            <img src="{{ asset('build/images/profile-placeholder.png') }}" alt="Client profile image">
                        </div>
                        <div class="profile-main-info">
                            <p class="user-fullname">Фамилия Имя Отчество</p>
                            <p class="user-location">г. Москва, ул. Якиманки 72, кв. 43</p>
                        </div>
                    </header>
                    <section class="user-about">
                        <h2>Информация о пользователе</h2>
                        <p>
                            <span>email</span>

                        </p>
                        <p>
                            <span>Номер телефона</span>

                        </p>
                    </section>
                    <a class="change-profile">Редактировать профиль</a>
                </main>
            </div>
        </div>
    </main>
{% endblock %}

templates/client/related_specialists.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <main class="user-profile-main">
        <div class="container">
            <div class="user-profile-content">
                <aside>
                    <nav class="user-nav">
                        <ul>
                            <li><a href="{{ path('app_client_show_order', { id: order.id}) }}">Мой заказ</a></li>
                            <li><a href="{{ path('app_client_homepage') }}">Мои заказы</a></li>
                            <li><a href="{{ path('app_client_profile') }}">Настройки</a></li>
                            <li><a class="logout" href="{{ path('app_logout') }}">Выйти</a></li>
                        </ul>
                    </nav>
                </aside>
                <main class="client-homepage-main-section">
                    <h1>Заказ: "{{ order.orderName }}"</h1>
                    <h2>Связанные с заказом специалисты</h2>
                    <div class="related_spec_list">
                        {% if not relatedSpecialists %}
                            <p style="font-size: 1.2rem">У этого заказа пока нет связанных специалистов. Пожалуйста предложите специалистам
                                выполнить данный заказ или долждитесь, когда не него откликнуться</p>
                        {% endif %}
                        {% for relatedSpecialist in relatedSpecialists %}
                            <div class="related_spec_item">
                                <div class="spec_name">
                                    <a href="{{ path('app_client_specialist_profile', { id: relatedSpecialist.specialist.id }) }}">
                                        {{ relatedSpecialist.specialist.userId.surname }}
                                        {{ relatedSpecialist.specialist.userId.firstName }}
                                        {{ relatedSpecialist.specialist.userId.patronymic }}
                                    </a>
                                </div>
                                <div>
                                    <p class="spec_order_mode">Выбранный вами или отклик</p>
                                    <p class="spec_contact_info">Контактные данные: <span>{{ relatedSpecialist.specialist.userId.phoneNumber }}</span></p>
                                </div>
                                <div>
{#                                    <form action="{{ path('app_client_related_specialists', { id: order.id }) }}" method="post">#}
{#                                        <input type="hidden" name="specialist_id" value="{{ relatedSpecialist.specialist.id }}">#}
{#                                        <button type="submit" class="order-cancel-btn"#}
{#                                        onclick="alert('Специалист назначен')">#}
{#                                            Назначить#}
{#                                        </button>#}
{#                                    </form>#}
                                    <a href="{{ path('app_client_appoint_specialist', { orderId: order.id, specId: relatedSpecialist.specialist.id }) }}"
                                       class="order-cancel-btn"
                                    >
                                        Назначить
                                    </a>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                </main>
            </div>
        </div>
    </main>
{% endblock %}

templates/client/update_order.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <div style="margin-top: 100px;">
        {{ form_start(updateForm) }}
            {{ form_widget(updateForm) }}

            <button type="submit">Сохранить изменения</button>

        {{ form_end(updateForm) }}
    </div>
{% endblock %}